#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v5
# autospec commit: c02b2fe
#
Name     : R-rstudioapi
Version  : 0.16.0
Release  : 99
URL      : https://cran.r-project.org/src/contrib/rstudioapi_0.16.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/rstudioapi_0.16.0.tar.gz
Summary  : Safely Access the RStudio API
Group    : Development/Tools
License  : MIT
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
messages when it's not.

%prep
%setup -q -n rstudioapi
pushd ..
cp -a rstudioapi buildavx2
popd
pushd ..
cp -a rstudioapi buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711315146

%install
export SOURCE_DATE_EPOCH=1711315146
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/rstudioapi/DESCRIPTION
/usr/lib64/R/library/rstudioapi/INDEX
/usr/lib64/R/library/rstudioapi/LICENSE
/usr/lib64/R/library/rstudioapi/Meta/Rd.rds
/usr/lib64/R/library/rstudioapi/Meta/features.rds
/usr/lib64/R/library/rstudioapi/Meta/hsearch.rds
/usr/lib64/R/library/rstudioapi/Meta/links.rds
/usr/lib64/R/library/rstudioapi/Meta/nsInfo.rds
/usr/lib64/R/library/rstudioapi/Meta/package.rds
/usr/lib64/R/library/rstudioapi/Meta/vignette.rds
/usr/lib64/R/library/rstudioapi/NAMESPACE
/usr/lib64/R/library/rstudioapi/NEWS.md
/usr/lib64/R/library/rstudioapi/R/rstudioapi
/usr/lib64/R/library/rstudioapi/R/rstudioapi.rdb
/usr/lib64/R/library/rstudioapi/R/rstudioapi.rdx
/usr/lib64/R/library/rstudioapi/doc/dialogs.R
/usr/lib64/R/library/rstudioapi/doc/dialogs.Rmd
/usr/lib64/R/library/rstudioapi/doc/dialogs.html
/usr/lib64/R/library/rstudioapi/doc/document-manipulation.R
/usr/lib64/R/library/rstudioapi/doc/document-manipulation.Rmd
/usr/lib64/R/library/rstudioapi/doc/document-manipulation.html
/usr/lib64/R/library/rstudioapi/doc/index.html
/usr/lib64/R/library/rstudioapi/doc/introduction.Rmd
/usr/lib64/R/library/rstudioapi/doc/introduction.html
/usr/lib64/R/library/rstudioapi/doc/projects.R
/usr/lib64/R/library/rstudioapi/doc/projects.Rmd
/usr/lib64/R/library/rstudioapi/doc/projects.html
/usr/lib64/R/library/rstudioapi/doc/r-session.R
/usr/lib64/R/library/rstudioapi/doc/r-session.Rmd
/usr/lib64/R/library/rstudioapi/doc/r-session.html
/usr/lib64/R/library/rstudioapi/doc/terminal.R
/usr/lib64/R/library/rstudioapi/doc/terminal.Rmd
/usr/lib64/R/library/rstudioapi/doc/terminal.html
/usr/lib64/R/library/rstudioapi/doc/visual-mode.R
/usr/lib64/R/library/rstudioapi/doc/visual-mode.Rmd
/usr/lib64/R/library/rstudioapi/doc/visual-mode.html
/usr/lib64/R/library/rstudioapi/help/AnIndex
/usr/lib64/R/library/rstudioapi/help/aliases.rds
/usr/lib64/R/library/rstudioapi/help/figures/logo.png
/usr/lib64/R/library/rstudioapi/help/figures/logo.svg
/usr/lib64/R/library/rstudioapi/help/paths.rds
/usr/lib64/R/library/rstudioapi/help/rstudioapi.rdb
/usr/lib64/R/library/rstudioapi/help/rstudioapi.rdx
/usr/lib64/R/library/rstudioapi/html/00Index.html
/usr/lib64/R/library/rstudioapi/html/R.css
/usr/lib64/R/library/rstudioapi/resources/bug-report.md
